<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Appointment Schedule - {{ $user->name }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; font-size: 13px; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #4f46e5; font-size: 24px; }
        .header h2 { margin: 5px 0 0; font-size: 18px; color: #555; }
        .doctor-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f3f4f6; color: #374151; font-weight: bold; }
        tr:nth-child(even) { background-color: #fafafa; }
        .status-pending { color: #d97706; font-weight: bold; }
        .status-accepted { color: #059669; font-weight: bold; }
        .status-completed { color: #2563eb; font-weight: bold; }
        .status-canceled { color: #dc2626; font-weight: bold; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>MediConnect</h1>
        <h2>Appointment Schedule</h2>
    </div>

    <div class="doctor-info">
        <strong>Doctor:</strong> Dr. {{ $user->first_name }} {{ $user->name }}<br>
        <strong>Generated On:</strong> {{ now()->format('F j, Y, g:i a') }}
    </div>

    @if($appointments->isEmpty())
        <p>No appointments found.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Date & Time</th>
                    <th>Patient Name</th>
                    <th>Patient Email</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($appointments as $app)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($app->appointment_date)->format('M d, Y') }} at {{ \Carbon\Carbon::parse($app->appointment_time)->format('g:i A') }}</td>
                        <td>{{ $app->patient->first_name }} {{ $app->patient->name }}</td>
                        <td>{{ $app->patient->email }}</td>
                        <td class="status-{{ $app->status }}">{{ ucfirst($app->status) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        This document is officially generated by the MediConnect system.
    </div>
</body>
</html>
