<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Medical History - {{ $user->name }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; font-size: 14px; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #4f46e5; font-size: 24px; }
        .header h2 { margin: 5px 0 0; font-size: 18px; color: #555; }
        .patient-info { margin-bottom: 30px; }
        .appointment { border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; page-break-inside: avoid; }
        .appointment h3 { margin-top: 0; color: #312e81; border-bottom: 1px solid #eee; padding-bottom: 5px; font-size: 16px; }
        .notes { background-color: #f9fafb; padding: 10px; border-left: 3px solid #4f46e5; margin-top: 10px; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>MediConnect</h1>
        <h2>Medical History Report</h2>
    </div>

    <div class="patient-info">
        <strong>Patient Name:</strong> {{ $user->first_name }} {{ $user->name }}<br>
        <strong>Email:</strong> {{ $user->email }}<br>
        <strong>Generated On:</strong> {{ now()->format('F j, Y, g:i a') }}
    </div>

    @if($appointments->isEmpty())
        <p>No completed appointments found in your medical history.</p>
    @else
        @foreach($appointments as $app)
            <div class="appointment">
                <h3>{{ \Carbon\Carbon::parse($app->appointment_date)->format('F j, Y') }} at {{ \Carbon\Carbon::parse($app->appointment_time)->format('g:i A') }}</h3>
                <p><strong>Doctor:</strong> Dr. {{ $app->doctor->first_name }} {{ $app->doctor->name }} ({{ $app->doctor->doctorProfile->specialization ?? 'General Practice' }})</p>
                
                @if($app->consultation_notes)
                    <div class="notes">
                        <strong>Consultation Notes:</strong><br>
                        {{ nl2br(e($app->consultation_notes)) }}
                    </div>
                @else
                    <p><em>No consultation notes provided.</em></p>
                @endif
            </div>
        @endforeach
    @endif

    <div class="footer">
        This document is officially generated by the MediConnect system.
    </div>
</body>
</html>
